apiVersion: v1
kind: Service
metadata:
  name: svc-sistema
spec:
  type: NodePort
  selector:
    app: sistema-noticias
  ports:
    - port: 80
      # targetPort: 80
      nodePort: 30002 # value from 30000 to 37k something
