---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $ENV_NAMESPACE
  labels:
    name: $SERVICE_NAME
    app: $SERVICE_NAME
spec:
  selector:
    app: $SERVICE_NAME
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - protocol: TCP
      port: $SERVICE_PORT
      targetPort: $CONTAINER_PORT
